blank_issues_enabled: false
contact_links:
  - name: ForgottenWorld Support
    url: https://forum.forgottenworld.it/c/supporto/8
    about: Please ask and answer questions here.
  - name: ForgottenWorld Security
    url: https://forum.forgottenworld.it/g/sviluppatore
    about: Please report security vulnerabilities here.
